### ISSUE TITLE
Error when including file to test with `karma`

### ISSUE THREAD

**Issue by cmgustavo** [bitpay/angular-bitcore-wallet-client#3]
```
 TypeError: 'undefined' is not a function (evaluating 'ec.curve.point.bind(ec.curve)')
  at /copay/bower_components/angular-bitcore-wallet-client/angular-bitcore-wallet-client.js:4731
```

**Comment by Giszmo** [comment]
I get `TypeError: 'undefined' is not a function (evaluating 'ec.curve.point.bind(ec.curve)')` when testing my app with `PhantomJS` but not when testing with `Chrome`.

It's these lines in my 100k LOC bundle:

```
var ec = require('elliptic').curves.secp256k1;
var ecPoint = ec.curve.point.bind(ec.curve);
var ecPointFromX = ec.curve.pointFromX.bind(ec.curve);
```

… wherever they may come from. Not sure if relevant here. I'm just getting started with `PhantomJS`.

@cmgustavo did you resolve your issue?

**Comment by cmgustavo** [comment]
No, I didn't. Maybe it 's an issue with PhantomJS, but I am not sure. BTW I didn't testing with Chrome.

**Comment by Giszmo** [comment]
@cmgustavo so you also run into this in phantomJS? If that's the case then we should probably check there. Anyway it would be an important detail to know for this issue.

**Comment by matiu** [comment]
fixed with phantom 2.x
